-- CREATE DATABASE StatsDB;
USE StatsDB;

CREATE TABLE IF NOT EXISTS Player (
    UID VARCHAR(255) NOT NULL,
    Name VARCHAR(255) NOT NULL,
    Score INT NOT NULL,
    Country CHAR(2) NOT NULL,
    created TIMESTAMP NOT NULL,
    PRIMARY KEY (UID)
);

